apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataspace-connector.fullname" . }}-config
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
type: Opaque
data:
{{- $path := printf "configs/%s/*" .Values.edc.connectorType }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
