openapi: 3.0.1
paths:
  /contractagreements:
    get:
      operationId: getAllAgreements
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
          format: int32
      - in: query
        name: limit
        schema:
          type: integer
          format: int32
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - in: query
        name: sortField
        schema:
          type: string
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContractAgreementDto'
          description: default response
      tags:
      - Contract Agreement
  /contractagreements/{id}:
    get:
      operationId: getContractAgreement
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractAgreementDto'
          description: default response
      tags:
      - Contract Agreement
components:
  schemas:
    ContractAgreementDto:
      type: object
      properties:
        assetId:
          type: string
        consumerAgentId:
          type: string
        contractEndDate:
          type: integer
          format: int64
        contractSigningDate:
          type: integer
          format: int64
        contractStartDate:
          type: integer
          format: int64
        id:
          type: string
        policyId:
          type: string
        providerAgentId:
          type: string
      required:
      - assetId
      - consumerAgentId
      - id
      - policyId
      - providerAgentId
