openapi: 3.0.1
paths:
  /contractnegotiations:
    get:
      operationId: getNegotiations
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
          format: int32
      - in: query
        name: limit
        schema:
          type: integer
          format: int32
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - in: query
        name: sortField
        schema:
          type: string
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContractNegotiationDto'
          description: default response
      tags:
      - Contract Negotiation
    post:
      operationId: initiateContractNegotiation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NegotiationInitiateRequestDto'
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NegotiationId'
          description: default response
      tags:
      - Contract Negotiation
  /contractnegotiations/{id}:
    get:
      operationId: getNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractNegotiationDto'
          description: default response
      tags:
      - Contract Negotiation
  /contractnegotiations/{id}/agreement:
    get:
      operationId: getAgreementForNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractAgreementDto'
          description: default response
      tags:
      - Contract Negotiation
  /contractnegotiations/{id}/cancel:
    post:
      operationId: cancelNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - Contract Negotiation
  /contractnegotiations/{id}/decline:
    post:
      operationId: declineNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - Contract Negotiation
  /contractnegotiations/{id}/state:
    get:
      operationId: getNegotiationState
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NegotiationState'
          description: default response
      tags:
      - Contract Negotiation
components:
  schemas:
    Action:
      type: object
      properties:
        constraint:
          $ref: '#/components/schemas/Constraint'
        includedIn:
          type: string
        type:
          type: string
    Constraint:
      type: object
      discriminator:
        propertyName: edctype
      properties:
        edctype:
          type: string
      required:
      - edctype
    ContractAgreementDto:
      type: object
      properties:
        assetId:
          type: string
        consumerAgentId:
          type: string
        contractEndDate:
          type: integer
          format: int64
        contractSigningDate:
          type: integer
          format: int64
        contractStartDate:
          type: integer
          format: int64
        id:
          type: string
        policy:
          $ref: '#/components/schemas/Policy'
        providerAgentId:
          type: string
      required:
      - assetId
      - consumerAgentId
      - id
      - policy
      - providerAgentId
    ContractNegotiationDto:
      type: object
      properties:
        contractAgreementId:
          type: string
        counterPartyAddress:
          type: string
        errorDetail:
          type: string
        id:
          type: string
        protocol:
          type: string
        state:
          type: string
        type:
          type: string
          enum:
          - CONSUMER
          - PROVIDER
    ContractOfferDescription:
      type: object
      properties:
        assetId:
          type: string
        offerId:
          type: string
        policy:
          $ref: '#/components/schemas/Policy'
      required:
      - assetId
      - offerId
      - policy
    Duty:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        consequence:
          $ref: '#/components/schemas/Duty'
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        parentPermission:
          $ref: '#/components/schemas/Permission'
        target:
          type: string
        uid:
          type: string
    NegotiationId:
      type: object
      properties:
        id:
          type: string
    NegotiationInitiateRequestDto:
      type: object
      properties:
        connectorAddress:
          type: string
        connectorId:
          type: string
        offer:
          $ref: '#/components/schemas/ContractOfferDescription'
        protocol:
          type: string
      required:
      - connectorAddress
      - connectorId
      - offer
      - protocol
    NegotiationState:
      type: object
      properties:
        state:
          type: string
    Permission:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
        target:
          type: string
        uid:
          type: string
    Policy:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - SET
          - OFFER
          - CONTRACT
        assignee:
          type: string
        assigner:
          type: string
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
        inheritsFrom:
          type: string
        obligations:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
        prohibitions:
          type: array
          items:
            $ref: '#/components/schemas/Prohibition'
        target:
          type: string
    Prohibition:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        target:
          type: string
        uid:
          type: string
