openapi: 3.0.1
paths:
  /callback/{processId}/deprovision:
    post:
      operationId: callDeprovisionWebhook
      parameters:
      - in: path
        name: processId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeprovisionedResource'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - HTTP Provisioner Webhook
  /callback/{processId}/provision:
    post:
      operationId: callProvisionWebhook
      parameters:
      - in: path
        name: processId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisionerWebhookRequest'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - HTTP Provisioner Webhook
components:
  schemas:
    DataAddress:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    DeprovisionedResource:
      type: object
      properties:
        error:
          type: boolean
        errorMessage:
          type: string
        inProcess:
          type: boolean
        provisionedResourceId:
          type: string
    ProvisionerWebhookRequest:
      type: object
      properties:
        apiToken:
          type: string
        assetId:
          type: string
        contentDataAddress:
          $ref: '#/components/schemas/DataAddress'
        hasToken:
          type: boolean
        resourceDefinitionId:
          type: string
        resourceName:
          type: string
      required:
      - assetId
      - contentDataAddress
      - resourceDefinitionId
      - resourceName
