openapi: 3.0.1
paths:
  /instances:
    get:
      operationId: getAll
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataPlaneInstance'
          description: default response
      tags:
      - Dataplane Selector
    post:
      operationId: addEntry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataPlaneInstance'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - Dataplane Selector
  /instances/select:
    post:
      operationId: find
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectionRequest'
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataPlaneInstance'
          description: default response
      tags:
      - Dataplane Selector
components:
  schemas:
    DataAddress:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    DataPlaneInstance:
      type: object
      properties:
        id:
          type: string
        lastActive:
          type: integer
          format: int64
        properties:
          type: object
          additionalProperties:
            type: object
        turnCount:
          type: integer
          format: int32
        url:
          type: string
          format: url
    SelectionRequest:
      type: object
      properties:
        destination:
          $ref: '#/components/schemas/DataAddress'
        source:
          $ref: '#/components/schemas/DataAddress'
        strategy:
          type: string
