name: Check New Pull Request

on:
  pull_request_target:
    types: [ opened ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
    steps:
      - name: Assign to basic project
        uses: srggrs/assign-one-project-github-action@1.3.1
        with:
          project: 'https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/projects/1'
          column_name: 'In progress'
