name: Publish Images to ECR

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  Publish:
    # run only on upstream repo
    if: github.repository_owner == 'mindsphere'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: true
      matrix:
        connector: [consumer, provider]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: catena-x-edc-connector
          IMAGE_TAG: ${{ github.sha }}-${{ matrix.connector }}
        run: |
          docker build -f ./launchers/mdsp-connector/${{ matrix.connector }}.Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
