name: publish artifacts

on:
  workflow_run:
    workflows:
    - "Test Code (Style, Tests)"
    - "CodeQL"
    - "Integration Tests"
    branches: [main]
    types:
      - completed

jobs:
  Publish:
    # run only on upstream repo
    if: github.repository_owner == 'eclipse-dataspaceconnector'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-build

      - run: ./gradlew clean -x test publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}